### ISSUE TITLE
Seal Description Page: Design Concept

### ISSUE THREAD

**Issue by thehabes** [thehabes/DigiSig#13]
I think we need to consider not tabulating the main result  here, if that is possible. What
information appears will vary greatly from case to case. Sometimes we have just an 
image. In other cases we have information for all the various possible fields. Another issue is 
that sometimes there will be a great deal of text so we need to allow lots of room to flow 
down the page.

**Comment by thehabes** [comment]
Notes:
1. Breaking from a tabulated view here means it will not follow the design concept of the rest of the site.  
2. In the tabulated view, we cannot pick and choose which columns to show because each row for multiple results could have different results and the tables will become unreadable.  
3. Allowing for empty cells means missing data in the database is easily identifiable.
4.  This is a common situation on the internet, and the general response is to build the table to represent all possible columns and populate empty cells with filler text.  This is user friendly, since the user knows what data to expect and is not alarmed by missing data and the organizational structure is consistent.

**Comment by johnmcewan** [comment]
I can tell you would like to leave things in a tabular form. The major problem is that sometime the information is in the image, and sometimes in the table. This means that we cannot populate any blank cells with 'information not available'. The sad truth is that most of the time the information is going to be in the image rather than the table so it is really the image that needs to take priority, at least in the short to medium term.

**Comment by thehabes** [comment]
Redesign implemented
