### ISSUE TITLE
seal page -- date -- in 'examples' table

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#52]
Dates are not being formatted correctly here. You can see the date reads ' 1970 - 1970', which is clearly wrong. I am not sure why they are rendering that way. In the data base the dates take the form of YEAR- MONTH- DAY - HOUR  (or something like that) and I asked Han if he could cut that down for display purposes to just the year. Whatever is happening right now is not working properly. So as a temporary fix I would suggest removing whatever code has been introduced to handle the date formatting here and just leave them for the moment in the long format. 
![screenshot 7](https://cloud.githubusercontent.com/assets/13589952/9335602/ccf7fe4a-4589-11e5-82d2-cc050deda162.png)

**Comment by thehabes** [comment]
This one is a little tricky, I will have to address it later.

**Comment by thehabes** [comment]
The date function used was not working well with php.  I picked a different way to do it that ensures the dates are correct.  It was also crucial to detect an empty date because otherwise it potentially picks a random one an populates.  I have added detection and push out a blank instead of a random date now.  Dates seem to be working, this needs testing.

**Comment by thehabes** [comment]
tesetd
