### ISSUE TITLE
login -- user email displayed on screen -- move to other side of search bar? 

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#72]
Once a user has logged in their email is displayed in the bar with 'home' , 'about' etc.... next to the log in button. This is problematic because all the other items in the bar can be clicked on to move you to another page whereas the email is just information.  Could you try moving to the left hand side of the bar instead? Alternatively, perhaps we could stick it in the upper left corner, over top of the banner?

**Comment by thehabes** [comment]
I think the user information should stay next to where login/logout is so that users are familiar with the area on the page and the user information will always reassure them that they are logged is as their user. 

I have changed the color to the dark blue and got rid of the pointy hand when hovering over it.  It blends in better and users will know that is not a clickable area.

If you still want it moved, this is entirely possible also.  You can let me know after you see it.

**Comment by thehabes** [comment]
This is acceptable for now.
